# Generated by Django 5.0.1 on 2024-01-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
